# Generated by Django 3.1 on 2021-03-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipsBlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='SDLT Tech Tips Blog', max_length=255),
        ),
    ]
