# Generated by Django 3.1 on 2021-03-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipsBlogApp', '0003_post_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snippet',
        ),
    ]
