# Generated by Django 3.1 on 2021-03-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipsBlogApp', '0003_auto_20210319_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='general tips', max_length=2500),
        ),
    ]
