# Generated by Django 3.1 on 2021-03-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipsBlogApp', '0004_remove_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click the link above to get the detailed tip/post', max_length=255),
        ),
    ]
